services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql
  api:
    build: .
    ports:
      - 4567:4567
    depends_on:
      - db
