volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  api:
    build: .
    command: rake db:reset & bundle exec ruby lib/app.rb
    image: api-sinatra
    ports:
      - 4567:4567
    depends_on:
      - postgres
    # restart: on-failure
